USE QuanLyChuyenBay
GO

--CAU 1
SELECT CHUYENBAY.MACB, LICHBAY.NGAYDI, KHACHHANG.TEN, KHACHHANG.DCHI, KHACHHANG.DTHOAI
FROM CHUYENBAY 
INNER JOIN LICHBAY ON CHUYENBAY.MACB = LICHBAY.MACB
INNER JOIN DATCHO ON LICHBAY.MACB = DATCHO.MACB
INNER JOIN KHACHHANG ON DATCHO.MAKH = KHACHHANG.MAKH
ORDER BY MACB ASC,  NGAYDI DESC
--CAU 2
SELECT PHANCONG.MACB, PHANCONG.NGAYDI, NHANVIEN.TEN, NHANVIEN.DCHI, NHANVIEN.DTHOAI
FROM NHANVIEN 
INNER JOIN PHANCONG ON NHANVIEN.MANV = PHANCONG.MANV
ORDER BY MACB ASC,  NGAYDI DESC
--CAU 3
SELECT PHANCONG.MACB, PHANCONG.NGAYDI, NHANVIEN.TEN
FROM NHANVIEN 
INNER JOIN PHANCONG ON NHANVIEN.MANV = PHANCONG.MANV
WHERE NHANVIEN.MANV = '1001'
--CAU 4
SELECT CHUYENBAY.MACB, CHUYENBAY.SBDI, CHUYENBAY.GIODI,CHUYENBAY.GIODEN, LICHBAY.NGAYDI
FROM CHUYENBAY
INNER JOIN LICHBAY ON CHUYENBAY.MACB= LICHBAY.MACB
WHERE CHUYENBAY.SBDEN LIKE N'DEN%'
ORDER BY LICHBAY.NGAYDI DESC, CHUYENBAY.SBDI ASC
--CAU 5 
SELECT LOAIMB.HANGSX, LOAIMB.MALOAI, NHANVIEN.TEN
FROM NHANVIEN
INNER JOIN KHANANG ON NHANVIEN.MANV= KHANANG.MANV
INNER JOIN LOAIMB  ON KHANANG.MALOAI = LOAIMB.MALOAI
--CAU 6
SELECT NHANVIEN.MANV, NHANVIEN.TEN,  PHANCONG.MACB
FROM NHANVIEN
INNER JOIN PHANCONG ON NHANVIEN.MANV= PHANCONG.MANV
WHERE PHANCONG.MACB LIKE N'100%' AND NGAYDI LIKE N'2000-10-31'
--CAU 7
SELECT CHUYENBAY.MACB, PHANCONG.NGAYDI, NHANVIEN.MANV, NHANVIEN.TEN
FROM NHANVIEN
JOIN PHANCONG ON NHANVIEN.MANV = PHANCONG.MANV
JOIN LICHBAY ON PHANCONG.NGAYDI = LICHBAY.NGAYDI
JOIN CHUYENBAY ON LICHBAY.MACB = CHUYENBAY.MACB
WHERE CHUYENBAY.SBDEN ='ORD'
--CAU 8
SELECT CHUYENBAY.MACB, NHANVIEN.MANV, NHANVIEN.TEN
FROM NHANVIEN
JOIN PHANCONG ON NHANVIEN.MANV = PHANCONG.MANV
JOIN LICHBAY ON PHANCONG.NGAYDI = LICHBAY.NGAYDI
JOIN CHUYENBAY ON LICHBAY.MACB = CHUYENBAY.MACB
WHERE LICHBAY.NGAYDI LIKE N'2000-10-31%' AND CHUYENBAY.SBDI LIKE N'MIA%' AND CHUYENBAY.GIODI LIKE N'20:30%'
--CAU 9
SELECT PHANCONG.MACB, SOHIEU, LOAIMB.MALOAI,HANGSX
FROM NHANVIEN
JOIN PHANCONG ON NHANVIEN.MANV = PHANCONG.MANV
JOIN KHANANG ON NHANVIEN.MANV = KHANANG.MANV
JOIN LOAIMB ON KHANANG.MALOAI = LOAIMB.MALOAI
JOIN MAYBAY ON LOAIMB.MALOAI = MAYBAY.MALOAI
WHERE NHANVIEN.TEN LIKE N'Quang%'
--CAU 10
SELECT NHANVIEN.TEN, NHANVIEN.MANV
FROM NHANVIEN 
LEFT JOIN PHANCONG ON NHANVIEN.MANV = PHANCONG.MANV
WHERE PHANCONG.MANV IS NULL


